name: Release Build

on:
  workflow_dispatch:
permissions: write-all
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          cache-all-crates: true

      - name: Install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Pnpm install
        run: |
          pnpm i

      - name: Tauri build
        uses: tauri-apps/tauri-action@v0
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: "Vesc Data Aanlysis v__VERSION__"
          releaseBody: "More new features are now supported."
          tauriScript: pnpm tauri
          args: --target ${{ matrix.target }}

      - name: Portable Bundle
        if: matrix.os == 'windows-latest'
        run: pnpm portable ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # release-update:
  #   runs-on: ubuntu-latest
  #   needs: [release, release-for-linux-arm]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "22"

  #     - uses: pnpm/action-setup@v4
  #       name: Install pnpm
  #       with:
  #         run_install: false

  #     - name: Pnpm install
  #       run: pnpm i

  #     - name: Release updater file
  #       run: pnpm updater
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # release-update-for-fixed-webview2:
  #   runs-on: ubuntu-latest
  #   needs: [release-for-fixed-webview2]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "22"

  #     - uses: pnpm/action-setup@v4
  #       name: Install pnpm
  #       with:
  #         run_install: false

  #     - name: Pnpm install
  #       run: pnpm i

  #     - name: Release updater file
  #       run: pnpm updater-fixed-webview2
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # submit-to-winget:
  #   runs-on: ubuntu-latest
  #   needs: [release-update]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Get Version
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install jq
  #         echo "VERSION=$(cat package.json | jq '.version' | tr -d '"')" >> $GITHUB_ENV
  #     - name: Submit to Winget
  #       uses: vedantmgoyal9/winget-releaser@main
  #       with:
  #         identifier: VescDataAnalysis.VescDataAnalysis
  #         version: ${{env.VERSION}}
  #         release-tag: v${{env.VERSION}}
  #         installers-regex: '_(arm64|x64|x86)-setup\.exe$'
  #         token: ${{ secrets.WINGET_TOKEN  }}